services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: src/PetFamily.API/Dockerfile
    ports:
       - "8080:8080"
    depends_on:
      - postgres
      - minio
      - seq
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    restart: always
  
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: pet_family
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  seq:
    container_name: seq
    image: datalust/seq:latest
    restart: always
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:5341"
      - "8081:80"
  
  minio:
    container_name: minio
    image: minio/minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" /data

  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - web
    restart: always
    
volumes:
  postgres-data:
  minio_data: